// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD26o4tu5ImNPVwiHndUQo0thxwOX707tk',
    appId: '1:598075725784:web:c2e0129745a34c740784ad',
    messagingSenderId: '598075725784',
    projectId: 'campiq-954bd',
    authDomain: 'campiq-954bd.firebaseapp.com',
    storageBucket: 'campiq-954bd.appspot.com',
    measurementId: 'G-02KD4B5N4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNP2pYZ1rjL5GN3phxLs0Ht96Hoenp1k',
    appId: '1:598075725784:android:d02ab595cca3eebd0784ad',
    messagingSenderId: '598075725784',
    projectId: 'campiq-954bd',
    storageBucket: 'campiq-954bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vUcbRuXtkIiVZLHb3vm5Hb8vTBhvgUQ',
    appId: '1:598075725784:ios:7ae58f6fc36b4d920784ad',
    messagingSenderId: '598075725784',
    projectId: 'campiq-954bd',
    storageBucket: 'campiq-954bd.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1vUcbRuXtkIiVZLHb3vm5Hb8vTBhvgUQ',
    appId: '1:598075725784:ios:7ae58f6fc36b4d920784ad',
    messagingSenderId: '598075725784',
    projectId: 'campiq-954bd',
    storageBucket: 'campiq-954bd.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );
}
